### ISSUE TITLE
Exception has occurred: FileNotFoundError

### ISSUE THREAD

**Issue by kefirek142** [RainFemboy/murrtube-downloader#1]
hey! sorry if this is dumb, i dunno if im just not doing something right, but every time i run the script i get this error:
![image](https://github.com/RainFemboy/murrtube-downloader/assets/165559363/dc7dc0b8-67a6-47bc-b75b-de17a7aa4bc8)

i'm pretty sure i have all the required modules

**Comment by zeozeozeo** [comment]
make sure you have ffmpeg installed: https://ffmpeg.org/download.html (you can put in in your PATH or in the same folder as you run the script from)

**Comment by RainFemboy** [comment]
Yeah looks like FFMpeg isnt installed, If you still are having issues after installing FFMpeg reopen the issue!
